### PR TITLE
Update setup-cowledmenace.tp2

### PR DESCRIPTION
**Pull request by RoxanneSHS**
version update

### CODE REVIEW

**Comment by RoxanneSHS** [comment]
Maybe you want to make a new github release as well, otherwise v0.2 can only be downloaded from master.

**Comment by Maltodaxtrin** [comment]
hey Roxanne, thanks for chipping in.

Still new to this whole github thing what's the difference between updating the master and making a new github release? Thanks!

**Comment by RoxanneSHS** [comment]
Basically you can use github as you like. For many of my mods I do not use the release system at all and the only existing version to use would be the master.
Release makes sense if more people work on a mod and make contributions via github and at a point decide that the new stuff is tested and ready for a new release. Other modders use github to store intermediate versions but want players to only use the released versions.
I mentioned it for your mod because you made a release before and now you have a new version as well, so there is ambiguity of which would be the right one you want people to use.

**Comment by Maltodaxtrin** [comment]
Well I'd like to have just 1 single release that's global but it doesn't seem like there's an easy way to do this on github.

I was looking for an easy way to just... delete everything and replace with new version but it wouldn't let me unless I manually deleted every single file. There should be an easy way to just, replace everything, unless there is and I haven't found it? Thanks!

**Comment by RoxanneSHS** [comment]
In your repository you simply click on the release tab and there should be a button that says "draft new release". If you click it you can add the version number and provide a change record. You do not need to do anything else because github will by default take a snapshot of the current master and make it the new release.
Afterwards you can continue to update the master until you decide that it is time for a new release.
You need not to delete anything or replace anything, the old release just goes into history.

**Comment by Maltodaxtrin** [comment]
Thank you Roxanne for your help now it's done! Will probably proceed like this in the future.

Much appreciated :)

**Pull request merged**
