### PR TITLE
update Simplified Chinese translation by Lewis Liu

### PR DESCRIPTION
**Pull request by Lzw104522773**
update Simplified Chinese translation by Lewis Liu

### CODE REVIEW

**Comment by Maltodaxtrin** [comment]
Hello Lewis,

Sorry for the delay, thank you so much for making this translation. I just updated the mod, there is only a difference of 1 line if you want to translate it. It is the following (line @630): "I suppose you'll be returning to Athkatla? This is goodbye then."

After that I could update the mod with your translation for sure :)

Thanks!

**Comment by Lzw104522773** [comment]
Ok ，I have done.

**Comment by Maltodaxtrin** [comment]
I think the old and the new should be merged together, as in English it says:

"I suppose you'll be returning to Athkatla? This is goodbye then. Thank you for your assistance in this matter, and may we meet again under better circumstances."

so in Chinese I think it should be something like:

我想，你会回到阿斯卡特拉吧？那么就再见吧。我感谢你在这件事上的协助，希望我们在更好的环境下再次相见

but I'm not sure if those 2 sentences together would work

**Comment by Lzw104522773** [comment]
Sorry, I didn't check carefully. It's alright now.

**Pull request closed without merging**
